### ISSUE TITLE
Error while using SSM Paramater store in URL

### ISSUE THREAD

**Issue by ngalanis930** [aws-samples/msk-config-providers#14]
I'm currently using MSK Config Providers 0.1.0 along with [Mongo Kafka Connector 1.10.0](https://github.com/mongodb/mongo-kafka/releases/tag/r1.10.0) to create my custom plugin in AWS MSK Connect.
When deploying the MSK connector and providing the mongodb `connection.uri` in plain text I have no issues and the connector comes up and working perfectly fine between AWS MSK and AWS DocDB. 
However, when inputting the MongoDB credentials using SSM Parameter store (created as Type secureString) the connector is failing. 
My relative code snippet is:
```
connector.class=com.mongodb.kafka.connect.MongoSinkConnector
config.providers=ssm
config.providers.ssm.param.region=us-east-1
config.providers.ssm.class=com.amazonaws.kafka.config.providers.SsmParamStoreConfigProvider
connection.uri=mongodb://myuser:${ssm::/docdb/mypassword}@myhost:27017/?ssl=true&retryWrites=false
```
The error I'm getting is:
```
There is an issue with the connector
Code: InvalidInput.InvalidConnectorConfiguration
Message: The connector configuration is invalid. Message: Connector configuration is invalid and contains the following 1 error(s):
Invalid value mongodb://myuser:${ssm::/docdb/mypassword}@myhost:27017/?ssl=true&retryWrites=false for configuration connection.uri: 
The connection string contains an invalid host 'myuser:${ssm::'. Reserved characters such as ':' must be escaped according RFC 2396. 
Any IPv6 address literal must be enclosed in '[' and ']' according to RFC 2732.
```
I've ran loads of tests trying to wrap up the mongodb connection string in SSM but I was getting pretty much the same error.
Any help would be much appreciated.

**Comment by bdesert** [comment]
thanks for your question, I will need to change the documentation. Config providers need to be defined in the worker config and not in the connector config. then `connection.uri` will be working properly.

**Comment by ngalanis930** [comment]
That's true! It works if it's defined in worker configuration.

**Comment by bdesert** [comment]
the documentation has been updated to mention that for MSK Connect, the providers needs to be configured in the worker configuration rather than connector config.
