### ISSUE TITLE
Which the earliest version for Apache Flink can use this feature?

### ISSUE THREAD

**Issue by guanlinz** [aws-samples/msk-config-providers#17]
I checked the KDA doc, and seems like the earliest version to support this is `v1.15.3`.

It is true? I didn't see anywhere write about the prerequests about use this feature

Thanks.

**Comment by bdesert** [comment]
I've checked Apache Flink sources, down to [version 1.10](https://github.com/apache/flink/blob/release-1.10.0/flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThread.java) - they all use KafkaConsumer to actually poll records from Kafka. That also means, that regular mechanisms of ConsumerConfig (Abstract Config) applied there.
So, if you add config providers to the [properties of your Flink app](https://nightlies.apache.org/flink/flink-docs-release-1.3/dev/connectors/kafka.html#kafka-consumer), and this JAR (will all the dependency libs) to the classpath, it should work.

Closing the issue. feel free to re-open if needed.
