### ISSUE TITLE
Solutions for cross-account Secret access

### ISSUE THREAD

**Issue by patrickherrera** [aws-samples/msk-config-providers#22]
I have a SASL/SCRAM secret for MSK (which must be in the same account as MSK) which I want to access through this Provider which is deployed to a different account than MSK.  All the appropriate roles and policies are in place and confirmed working.

However, I am unable to pass an ARN to the required Secret, only the Name, which then fails as it doesn't exist in the account running our Kafka Connect cluster.  Passing an ARN fails to parse as the upstream config parser is expecting the use of `:` as a separator: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/AbstractConfig.java#L92

I can see no way to suggest a different separator.

We are running Kafka Connect in an ECS Cluster and even if we were to assume a Role into the account containing the Secret, we have other Secrets (DB credentials for one of the Connectors) that are NOT in the MSK account so we are back to square one.  There is a [PR](https://github.com/jcustenborder/kafka-config-provider-aws/pull/14/files) up for an alternate implementation of this Provider that supports assuming a role just for looking up Secrets so it doesn't affect the Role being used by the rest of the application, but it can't be configured on a per-Secret basis, only for the whole Provider at the Kafka Connect cluster level.

One solution is to allow configuring some sort of post-parse substitution before the Secret is looked up [here](https://github.com/aws-samples/msk-config-providers/blob/trunk/src/main/java/com/amazonaws/kafka/config/providers/SecretsManagerConfigProvider.java#L131).  So you can pass in config like `${secretsmanager:arn|aws|secretsmanager|ap-southeast-2|123456789|secret|AmazonMSK_mySecret:ssl_trust_pass}` and then configure the Provider to convert `|` back to `:`.

Surely there is a better way?

**Comment by bdesert** [comment]
thanks for submitting the issue. I agree, this is a valid use case and valid request.
mentioned above [PR](https://github.com/jcustenborder/kafka-config-provider-aws/pull/14/files) assumes adding capabilities to assume roles or using access/secrets key. I think it also can be useful, but I would like to decouple features for assuming roles and using ARN for cross-account access to the secrets manager.

Secrets (individually) can can control access for cross account use cases. This is regulated by [permissions policies](https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples.html?icmpid=docs_asm_help_panel#auth-and-access_examples_read). I would suggest to keep this issue for implementing ARN-based retrieval, and have another issue for alternative authentications. This can be implemented for all providers as a base functionality.

LMK what you think

**Comment by patrickherrera** [comment]
Thanks @bdesert, I'm happy with that.  I'm testing a patched version that implements my suggestion above and it works fine.
I'm currently allowing the user to set it via a param, i.e.: `config.providers.secretsmanager.param.separator.replacement`.  It defaults to empty string so no substitution is made, otherwise whatever String is specified will be replaced with `:` before making any AWS calls.
Not sure how much more generic to make this, and does it make sense for SSM and S3?  I started to look at SSM but it looks like only name is supported by `software/amazon/awssdk/services/ssm/model/GetParameterRequest.java`.

Anyway, happy to share a PR when I can tidy it up, but any suggestions for implementation are welcome if you don't beat me to it

**Comment by bdesert** [comment]
SSM and S3 are not an issue.
SSM support cross account simply because the name of the params is a third param, which is not parseable and used as is (tested using unit test, but feel free to retest). Since SSM client API supports either name (in current account) or ARN, it will work if you just provide arn as is:
`${ssm::arn:aws:ssm:us-west-2:0123456789:parameter/my-parameter`

S3 is also support, because you have to provide a bucket name, which is unique regardless of an account it belongs to.

I will review the PR when submitted, please include additional test cases to cover new functionality. and thanks for reporting **and** contributing!

**Comment by bdesert** [comment]
@patrickherrera, I reviewed the PR and I'll add some comments, but after thinking a little about the proposed solution, I wanted to check with you another alternative solution: I recommend to URL Encode values for the secret names.
This way we will avoid using additional param for replacement.

Example, the value you used above will look:
`${secretsmanager:arn%3Aaws%3Asecretsmanager%3Aap-southeast-2%3A123456789%3Asecret%3AAmazonMSK_mySecret:ssl_trust_pass}`

Let me know what you think

**Comment by patrickherrera** [comment]
> `${secretsmanager:arn%3Aaws%3Asecretsmanager%3Aap-southeast-2%3A123456789%3Asecret%3AAmazonMSK_mySecret:ssl_trust_pass}`

Totally agree that is a better solution.  The only thing is that we are introducing a small assumption that `%` could never be a valid character, and assumptions about allowable characters are what got us here in the first place 😄 
I'm happy with that and we can update docs to encourage people to URL encode all the time regardless of whether they think they need it or not
